Chore/support multiple properties types
RafPe/serverless-reqvalidator-plugin pull request #31
Opened 2022-12-26 10:50 UTC by amuslija

Hey @RafPe!

My team and I are migrating our stack to use the latest version of Serverless (upgrade from version [1.83.0](https://www.npmjs.com/package/serverless/v/1.83.0) to version [3.26.0](https://www.npmjs.com/package/serverless/v/3.26.0). We heavily rely on [serverless-reqvalidator-plugin](https://github.com/RafPe/serverless-reqvalidator-plugin) to execute various validations (i.e. params and body content).

As part of that migration, we've upgraded `serverless-reqvalidator-plugin` to the [latest version](https://www.npmjs.com/package/serverless-reqvalidator-plugin/v/2.0.0), however we discovered that the plugin configuration does not support `object` types for the `reqValidatorName` property. This yields the following warning:

```bash
Warning: Invalid configuration encountered
  at 'functions.functionName.events.0.http.reqValidatorName': must be string
```

At the time of writing, Serverless does not error on configuration validation, but for the upcoming version 4.0.0 release, the framework will be treating the [warning as an error](https://www.serverless.com/framework/docs/deprecations).

To ensure that the plugin configuration works by default without throwing an error, I've extended the existing properties spec of `serverless-reqvalidator-plugin` to also support `object` type.

I've tested this locally by linking the dependency to my plugin fork, and the Serverless CLI no longer yields any errors.

Please let me know if you have any concerns.

Cheers.

2022-12-26 11:11 UTC, RafPe commented
Hey @amuslija ! Thank you very much for preparing this PR. I would be more than happy to merge this and make sure the community benefits from your contribution. 

As i have made some "booboos" in the past - would it be possible from your side to add a simple test before we release a major version upgrade ?

2022-12-26 14:11 UTC, amuslija commented
Thanks for your fast response @RafPe. As per your suggestion:
1. We could extend the current PR to include simple `jest` tests for just the schema validation part
2. We could put up a new PR with a general test suite (I hope I'm not missing something, but I cannot find any existing test suites for this plugin).

Also, keep in mind that this PR bumps the version of the plugin from `2.0.0` to `2.0.1`. 

Cheers!

2022-12-26 15:01 UTC, RafPe commented
@amuslija So this is the unfortunate story about this plugin that I have never implemented any tests. So I think it would be great if you could contribute to these. 

I think the proposal to split it into two separate PRs is very good.Lets start with test for the schema validation in this PR and create another one for general suite of tests for the plugin. 

Now regarding the version I would propose to bump it into 3.0.0 and start our co-op there. It would give 100% certainty we do not affect anyone in the 2.x.x landscape with our actions. And once we can have tests on board creating pipeline with matrix testing will enable us to be more robust in pushing out new versions.

2022-12-26 15:02 UTC, RafPe requested changes

2022-12-26 15:02 UTC, RafPe commented on package.json
> +  "version": "2.0.1",
Lets make your contribution an opening to v3 by changing this to major release

2022-12-27 12:20 UTC, RafPe requested changes

2022-12-27 12:20 UTC, RafPe commented on package.json
> +  "version": "3.0.0git config --global core.whitespace cr-at-eol",
Typo ? 🤔

2022-12-27 12:21 UTC, amuslija commented on package.json
> +  "version": "3.0.0git config --global core.whitespace cr-at-eol",
🤦 Fixed!

2022-12-27 12:31 UTC, RafPe commented
@amuslija I just run the test on my end 💪 Appreciate you preparing this 
```
  serverless-reqvalidator-plugin schema
    ✓ should validate a configuration without reqValidatorName property (3 ms)
    ✓ should validate a configuration with a local reqValidatorName property
    ✓ should validate a configuration with an external reqValidatorName property
    ✓ should not validate a configuration with an invalid reqValidatorName property

Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        0.258 s
Ran all test suites matching /test/i.
```

Let us make this happen :)

2022-12-27 12:31 UTC, RafPe approved these changes
🚀  lgtm

2022-12-27 12:32 UTC, merged

2022-12-29 18:27 UTC, chippyash commented
@amuslija @RafPe superb bit of cooperation chaps. Thank you so much for fixing your problem and hopefully everyone else's too. 🙏